# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: igg 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "igg"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["eiffel qiu"]
  s.date = "2015-01-19"
  s.description = "ImpactJS Game Generator for fast development"
  s.email = "eiffelqiu@qq.com"
  s.executables = ["igg"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/igg.rb",
    "lib/igg/builder/entity_builder.rb",
    "lib/igg/builder/level_builder.rb",
    "lib/igg/builder/project_builder.rb",
    "lib/igg/builder/templates/entity/entity.tt",
    "lib/igg/builder/templates/level/level.tt",
    "lib/igg/builder/templates/level/main.js",
    "lib/igg/builder/templates/project/04b03.font.png",
    "lib/igg/builder/templates/project/index.html",
    "lib/igg/builder/templates/project/main.tt",
    "lib/igg/builder/templates/project/sounds/death.mp3",
    "lib/igg/builder/templates/project/sounds/death.ogg",
    "lib/igg/builder/templates/project/sounds/jump.mp3",
    "lib/igg/builder/templates/project/sounds/jump.ogg",
    "lib/igg/builder/templates/project/sounds/shoot.mp3",
    "lib/igg/builder/templates/project/sounds/shoot.ogg",
    "lib/igg/builder/templates/project/sounds/theme.mp3",
    "lib/igg/builder/templates/project/sounds/theme.ogg",
    "lib/igg/cli.rb",
    "lib/igg/ext/method_hooker.rb",
    "lib/igg/ext/string_extention.rb"
  ]
  s.homepage = "http://github.com/eiffelqiu/igg"
  s.licenses = ["GPL2"]
  s.rubygems_version = "2.2.2"
  s.summary = "ImpactJS Game Generator"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
    else
      s.add_dependency(%q<thor>, ["~> 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
  end
end

